### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by knservis** [CommBank/grimlock#67] opened 2017-05-24 12:19 UTC
Hi J, 

I was going to build the project but many dependencies haven't been published on the external repos. 
```
[error] (*:coursierResolution) coursier.ResolutionException: Encountered 4 error(s) in dependency resolution:
[error]   au.com.cba.omnia:uniform-dependency;sbtVersion=0.13;scalaVersion=2.10:1.14.2-20161220001943-4f352b6:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/au.com.cba.omnia/uniform-dependency/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/au.com.cba.omnia/uniform-dependency/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       /Users/xxx/.ivy2/local/au.com.cba.omnia/uniform-dependency/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/au/com/cba/omnia/uniform-dependency_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-dependency-1.14.2-20161220001943-4f352b6.pom
[error]       http://commbank.artifactoryonline.com/commbank/ext-releases-local-ivy/au/com/cba/omnia/uniform-dependency_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-dependency-1.14.2-20161220001943-4f352b6.pom
[error]       http://commbank.artifactoryonline.com/commbank/ext-releases-local/au/com/cba/omnia/uniform-dependency_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-dependency-1.14.2-20161220001943-4f352b6.pom
[error]       https://repository.cloudera.com/artifactory/cloudera-repos/au/com/cba/omnia/uniform-dependency_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-dependency-1.14.2-20161220001943-4f352b6.pom
[error]   au.com.cba.omnia:uniform-core;sbtVersion=0.13;scalaVersion=2.10:1.14.2-20161220001943-4f352b6:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/au.com.cba.omnia/uniform-core/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/au.com.cba.omnia/uniform-core/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       /Users/xxx/.ivy2/local/au.com.cba.omnia/uniform-core/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/au/com/cba/omnia/uniform-core_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-core-1.14.2-20161220001943-4f352b6.pom
[error]       http://commbank.artifactoryonline.com/commbank/ext-releases-local-ivy/au/com/cba/omnia/uniform-core_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-core-1.14.2-20161220001943-4f352b6.pom
[error]       http://commbank.artifactoryonline.com/commbank/ext-releases-local/au/com/cba/omnia/uniform-core_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-core-1.14.2-20161220001943-4f352b6.pom
[error]       https://repository.cloudera.com/artifactory/cloudera-repos/au/com/cba/omnia/uniform-core_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-core-1.14.2-20161220001943-4f352b6.pom
[error]   au.com.cba.omnia:uniform-assembly;sbtVersion=0.13;scalaVersion=2.10:1.14.2-20161220001943-4f352b6:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/au.com.cba.omnia/uniform-assembly/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/au.com.cba.omnia/uniform-assembly/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       /Users/xxx/.ivy2/local/au.com.cba.omnia/uniform-assembly/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/au/com/cba/omnia/uniform-assembly_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-assembly-1.14.2-20161220001943-4f352b6.pom
[error]       http://commbank.artifactoryonline.com/commbank/ext-releases-local-ivy/au/com/cba/omnia/uniform-assembly_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-assembly-1.14.2-20161220001943-4f352b6.pom
[error]       http://commbank.artifactoryonline.com/commbank/ext-releases-local/au/com/cba/omnia/uniform-assembly_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-assembly-1.14.2-20161220001943-4f352b6.pom
[error]       https://repository.cloudera.com/artifactory/cloudera-repos/au/com/cba/omnia/uniform-assembly_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-assembly-1.14.2-20161220001943-4f352b6.pom
[error]   au.com.cba.omnia:uniform-thrift;sbtVersion=0.13;scalaVersion=2.10:1.14.2-20161220001943-4f352b6:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/au.com.cba.omnia/uniform-thrift/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/au.com.cba.omnia/uniform-thrift/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       /Users/xxx/.ivy2/local/au.com.cba.omnia/uniform-thrift/scala_2.10/sbt_0.13/1.14.2-20161220001943-4f352b6/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/au/com/cba/omnia/uniform-thrift_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-thrift-1.14.2-20161220001943-4f352b6.pom
[error]       http://commbank.artifactoryonline.com/commbank/ext-releases-local-ivy/au/com/cba/omnia/uniform-thrift_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-thrift-1.14.2-20161220001943-4f352b6.pom
[error]       http://commbank.artifactoryonline.com/commbank/ext-releases-local/au/com/cba/omnia/uniform-thrift_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-thrift-1.14.2-20161220001943-4f352b6.pom
[error]       https://repository.cloudera.com/artifactory/cloudera-repos/au/com/cba/omnia/uniform-thrift_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-thrift-1.14.2-20161220001943-4f352b6.pom
```

**Comment by poojke** [comment] 2017-05-25 05:44
Hi K,

Nice to hear from you 😄 Hope all is going well.

Sorry about the dependencies. Not sure why they can't be found. It seems to be all uniform related and that's all public. It does seem to be available on from (public) Artifactory. Let me try at home tonight, it was working as far as I know. 

Cheers,
J

**Comment by poojke** [comment] 2017-05-25 08:37
@knservis, not sure why you're running into issue. I'm not able to reproduce (even after deleting `~/.ivy2/cache/scala_2.10/') - see sbt assembly output below. Could you check again?

```
[info] downloading http://commbank.artifactoryonline.com/commbank/ext-releases-local-ivy/au/com/cba/omnia/uniform-core_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-core-1.14.2-20161220001943-4f352b6.jar ...
[info] 	[SUCCESSFUL ] au.com.cba.omnia#uniform-core;1.14.2-20161220001943-4f352b6!uniform-core.jar (2363ms)
[info] downloading http://commbank.artifactoryonline.com/commbank/ext-releases-local-ivy/au/com/cba/omnia/uniform-dependency_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-dependency-1.14.2-20161220001943-4f352b6.jar ...
[info] 	[SUCCESSFUL ] au.com.cba.omnia#uniform-dependency;1.14.2-20161220001943-4f352b6!uniform-dependency.jar (1506ms)
[info] downloading http://commbank.artifactoryonline.com/commbank/ext-releases-local-ivy/au/com/cba/omnia/uniform-assembly_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-assembly-1.14.2-20161220001943-4f352b6.jar ...
[info] 	[SUCCESSFUL ] au.com.cba.omnia#uniform-assembly;1.14.2-20161220001943-4f352b6!uniform-assembly.jar (1481ms)
[info] downloading http://commbank.artifactoryonline.com/commbank/ext-releases-local-ivy/au/com/cba/omnia/uniform-thrift_2.10_0.13/1.14.2-20161220001943-4f352b6/uniform-thrift-1.14.2-20161220001943-4f352b6.jar ...
[info] 	[SUCCESSFUL ] au.com.cba.omnia#uniform-thrift;1.14.2-20161220001943-4f352b6!uniform-thrift.jar (1482ms)
```

**Comment by poojke** [comment] 2017-06-04 21:35
@knservis please let me know if you still face the issue, if not I'll close the issue by week's end.

**Closed** 2017-06-12 00:04 UTC
